QUESTION 2:
    Accept two lists of 5 elements each from user.
    convert them to a numpy array. concatenate these arrays and print it. Also these arrays and print it.

In [7]:
lst1=[]
for i in range(5):
    ele1=int(input())
    lst1.append(ele1)
print(lst1)

lst2=[]
for i in range(5):
    ele2=int(input())
    lst2.append(ele2)
print(lst2)
import numpy
import numpy as np
arr1=np.array(lst1)
arr2=np.array(lst2)
print(arr1)
print(arr2)
print(type(arr1))
print(type(arr2))
arr=np.concatenate((arr1,arr2))
print("The concatenate form of those arrays",arr)
arr.sort()
print("The sortage form of those arrays",arr)




9
6
9
3
8
[9, 6, 9, 3, 8]
0
5
6
1
2
[0, 5, 6, 1, 2]
[9 6 9 3 8]
[0 5 6 1 2]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[9 6 9 3 8 0 5 6 1 2]
[0 1 2 3 5 6 6 8 9 9]


QUESTION 3:
Write a snippet to find the dimension of a ndarray and its size.

In [10]:
arr=np.array([[2,3,5],[6,8,9],[3,7,0]])
print(arr)
print("Dimension of the array:",arr.ndim)
print("Size of the array:",arr.size)

[[2 3 5]
 [6 8 9]
 [3 7 0]]
Dimension of the array: 2
Size of the array: 9


QUESTION 4:
How to convert a 1D array into 2D array? Demonstrate with the help of a code snippet.
    

In [7]:
import numpy as np
arr=np.arange(int(input()))
print("Test 1D array (shape)",arr.shape)
twod_array_row=arr[np.newaxis,:]
print("Test 2D array for row is:",twod_array_row.shape)
twod_array_col=arr[:,np.newaxis]
print("Test 2D array for column is:",twod_array_col.shape)





10
Test 1D array (shape) (10,)
Test 2D array for row is: (1, 10)
Test 2D array for column is: (10, 1)


QUESTION 5:
Consider two square numpy arrays. Stack them vertically and horizontally.

In [14]:
import numpy as geek
arr1=geek.array([[6,8,3],[7,9,0],[5,7,2]])
print(arr1)
arr2=geek.array([[7,9,0],[3,7,1],[2,5,3]])
print(arr2)
arr_hs=geek.hstack((arr1,arr2))
print("output horizontally stacked array:\n",arr_hs )
arr_vr=geek.vstack((arr1,arr2))
print("output vertically stacked array:\n",arr_vr)


[[6 8 3]
 [7 9 0]
 [5 7 2]]
[[7 9 0]
 [3 7 1]
 [2 5 3]]
output horizontally stacked array:
 [[6 8 3 7 9 0]
 [7 9 0 3 7 1]
 [5 7 2 2 5 3]]
output vertically stacked array:
 [[6 8 3]
 [7 9 0]
 [5 7 2]
 [7 9 0]
 [3 7 1]
 [2 5 3]]


QUESTION 6:
How to get unique items and counts of unique items.

In [3]:
lst=[1,6,6,9,0,9,3,0,4,7]

my_set=set(lst)
my_new_list= list(my_set)
print("unique numbers:",my_new_list)


unique numbers: [0, 1, 3, 4, 6, 7, 9]


In [6]:
lst=[1,6,6,9,0,9,3,0,4,7]
ll=[]
count=0

for i in lst:
    if i not in ll:
        
        count+=1
        ll.append(i)
    
print(count)

    

7
